version: '3.8'
services:
  db:
    image: postgres:14.1
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123
    ports:
      - "5433:5432"
  app:
    image: myspringapp
    container_name: app
    depends_on:
    - db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=123
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
    - "8080:8080"